### ISSUE TITLE
support for Node v19^

### ISSUE THREAD

**Issue by ayushanand18** [Doist/typist#255]
## Overview
Thanks for the great library! 
I tried installing it on my environment however, since my Node version is 19.9.0 the install failed because the engine was not supported. I get this error.

```sh
$ npm install
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: @doist/reactist@20.3.0
npm ERR! notsup Not compatible with your version of node/npm: @doist/reactist@20.3.0
npm ERR! notsup Required: {"node":"^16.0.0 || ^18.0.0","npm":"^8.3.0 || ^9.0.0"}
npm ERR! notsup Actual:   {"npm":"9.6.3","node":"v19.9.0"}
```
Is the team planning to add support v19+?

## Additional Details
details | version
---|---
node | 19.9.0
npm | 9.6.3

Thanks!

**Comment by ayushanand18** [comment]
Thanks a ton @rfgamaral! Noted your point. 
I was actually searching for a similar tool (as `fnm`) and I thank you for suggesting.

**Comment by rfgamaral** [comment]
Glad I could help. Let me know if you need anything else.

Closing this for now.
