### ISSUE TITLE
@mention suggestion extension does not work

### ISSUE THREAD

**Issue by Sandeep-Tech** [Doist/typist#47]
The below example was taken from official documentation

https://stackblitz.com/edit/souk-doist-typist-demo?file=src%2FApp.js,src%2FEditor.js

One would expect to see the log statements in the render function printed but we don't.

**Comment by rfgamaral** [comment]
> One would expect to see the log statements in the render function printed but we don't.

The render function is named [`dropdownRenderFn`](https://github.com/Doist/typist/blob/main/src/factories/create-suggestion-extension.ts#L85), but you are using `popupRenderFn`. Please try to change the name and see if this works for you, if it doesn't, feel free to reopen the issue.

**Comment by Sandeep-Tech** [comment]
I see, this works. The example in the [documentation](https://typist.doist.dev/?path=/docs/documentation-usage-extensions--page) used `popupRenderFn` instead of  `dropdownRenderFn`.
I have created a PR #50 to fix this. Please take a look.
