### ISSUE TITLE
Override suggestion markdown serializer function.

### ISSUE THREAD

**Issue by Sandeep-Tech** [Doist/typist#65]
My use case requires me to return a custom URL based on the ID string.
i.e. return something like `` `[${label}](matrix.to/${id})` `` instead of returning `` `[${label}](${attributeType}://${id})` ``

Thank you

**Comment by Sandeep-Tech** [comment]
@rfgamaral  Yes, that's exactly what I meant to say, a **generic override mechanism** so I can implement my use case specific output logic. Thanks again.

**Comment by rfgamaral** [comment]
> Instead, what we could do, is to provide a generic override mechanism, where you could add your own rules (for both serializers). You could even copy and paste the built-in one, and adapt it to your syntax.

Unfortunately, I misjudge the work required to implement a generic override mechanism, and after some careful consideration with the team, we've decided not to go forward with this feature.

The reason being that both the HTML and Markdown serializers are directly used by some built-in extensions, and providing a generic override mechanism while making sure that all usages of said serializers worked as expect, would introduce a certain complexity and added maintainability to the project for a feature that we don't need.

As a workaround, I suggest that you introduce some kind of pre- / post-processor on your side. By taking advantage of the `${attributeType}`, you can define a custom suggestion schema that should allow you to have a simple RegExp to do some find/replace magic where needed.

Thank you again for taking the time to contribute to Typist.

**Comment by Sandeep-Tech** [comment]
Sure, makes sense. I have gone ahead with 'pre/post processing the suggestion string' using RegExp in my project. Thank you.
